/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
Downloading: "https://download.pytorch.org/models/mvit_v2_s-ae3be167.pth" to /home/luke/.cache/torch/hub/checkpoints/mvit_v2_s-ae3be167.pth
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 132M/132M [00:05<00:00, 25.7MB/s]
Step 0/64000
----------
Traceback (most recent call last):
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 335, in <module>
    main()
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 330, in main
    train(run, recover=args.recover)
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 156, in train
    model_output = mvitv2s(data)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 558, in forward
    x, thw = block(x, thw)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 384, in forward
    x_attn, thw_new = self.attn(x_norm1, thw)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 293, in forward
    k, k_thw = self.pool_k(k, thw)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 89, in forward
    x = x.reshape((B * N, C) + thw).contiguous()
RuntimeError: shape '[4, 96, 8, 56, 56]' is invalid for input of size 19267584
Traceback (most recent call last):
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 335, in <module>
    main()
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 330, in main
    train(run, recover=args.recover)
  File "/home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py", line 156, in train
    model_output = mvitv2s(data)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 558, in forward
    x, thw = block(x, thw)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 384, in forward
    x_attn, thw_new = self.attn(x_norm1, thw)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 293, in forward
    k, k_thw = self.pool_k(k, thw)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/miniconda3/envs/wlasl/lib/python3.10/site-packages/torchvision/models/video/mvit.py", line 89, in forward
    x = x.reshape((B * N, C) + thw).contiguous()
RuntimeError: shape '[4, 96, 8, 56, 56]' is invalid for input of size 19267584
